apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    component: web-pod
spec:
  containers:
    - name: web-con
      image: nginx
      livenessProbe:
          httpGet:
            path: /
            port: 80
      readinessProbe: 
          httpGet:
            path: /
            port: 80
      ports:
        - containerPort: 80
          name: web-port
