apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    component: api-pod
spec:
  containers:
    - name: api-con
      image: gcr.io/simplicate-sparrow-project/api-small
      livenessProbe:
          httpGet:
            path: /api/health/alive
            port: 80
      readinessProbe: 
          httpGet:
            path: /api/health/ready
            port: 80
      env:
        - name: DB_HOST
          value: db-svc
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: sparrow
        - name: DB_USERNAME
          value: sparrow
        - name: DB_PASSWORD
          value: password
      ports:
        - containerPort: 80
          name: api-port
