apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
    - name: sparrow-db
      image: postgres
      env:
        - name: POSTGRES_DB
          value: sparrow
        - name: POSTGRES_USER
          value: sparrow
        - name: POSTGRES_PASSWORD
          value: password
      ports:
        - containerPort: 5432
          name: database
