apiVersion: v1
kind: Service
metadata:
  name: graylog-svc
  namespace: infrastructure
  labels:
    component: graylog-svc
spec:
  ports:
    - port: 9000
      targetPort: graylog-ui
  selector:
    component: graylog-pod
