version: '2'
services:

  lb:
    image: dockercloud/haproxy
    depends_on:
      - api
      - web
    links:
      - api
      - web
    environment:
      - ADDITIONAL_SERVICES=project_dir:web,project_dir:api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  web:  
    image: web
    ports:
      - "81:80"
    environment:
      #TCP_PORTS: "80"
      VIRTUAL_HOST: "*"
      VIRTUAL_HOST_WEIGHT: 0 
  
  api:  
    image: api
    ports:
      - "82:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: "*/api/*"
      VIRTUAL_HOST_WEIGHT: 1
      #TCP_PORTS: "8080" 
      DB_HOST: db
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"

  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
